
version: '3.8'

services:
    app:
        build: /home/univalle/Descargas/h/go_sqlite
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        command: ["go", "run", "main.go"]